name: GitHub Markdown Links
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  test-links:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: >-
          sudo apt-get install -y
          pandoc
      - uses: actions/checkout@v3
      - run: |
          find . -name '*.html' -delete
      - run: |
          find . -name '*.md' -exec pandoc -i {} -o {}.html \;
      - uses: anishathalye/proof-html@v2
        with:
          directory: .
          check_favicon: false
          ignore_empty_alt: true
          ignore_missing_alt: true
          ignore_url_re: |
            ^https:\/\/twitter.com\/CleanlabAI